language: python
python:
  - "2.7"
env:
  - DJANGO=Django==1.6 DB=sqlite
  - DJANGO=Django==1.6 DB=mysql
  - DJANGO=Django==1.6 DB=postgresql
install:
  - pip install -q -r requirements/all.txt --use-mirrors
  - pip install -q $DJANGO --use-mirrors
before_script:
  - python -c "import django; print(django.get_version())"
  - sudo apt-get install libjpeg-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib
  - pip install -I PIL
  - mysql -e 'create database openads_test;'
  - psql -c 'create database openads_test;' -U postgres
script:
    - python manage.py test -v 2
